// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafetyApplication.Data;

#nullable disable

namespace SafetyAppliaction.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241023034354_AddEmailToEmployee")]
    partial class AddEmailToEmployee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("SafetyAppliaction.Models.ApprovalWorkflow", b =>
                {
                    b.Property<int>("WorkflowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApprovalStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("AssignedEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StepNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("WorkflowId");

                    b.HasIndex("ApprovalStatusId");

                    b.HasIndex("AssignedEmployeeId");

                    b.HasIndex("RequestId");

                    b.ToTable("ApprovalWorkflows");
                });

            modelBuilder.Entity("SafetyAppliaction.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdminId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeptHeadId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SecretaryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(5871),
                            DepartmentName = "HR",
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(5887)
                        },
                        new
                        {
                            DepartmentId = 2,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(5888),
                            DepartmentName = "IT",
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(5889)
                        },
                        new
                        {
                            DepartmentId = 3,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(5890),
                            DepartmentName = "Finance",
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(5890)
                        });
                });

            modelBuilder.Entity("SafetyAppliaction.Models.RequestTransaction", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CounterMeasure")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MostDangerPoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PotentialDangerousPoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("RequestId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("StatusId");

                    b.ToTable("RequestTransactions");
                });

            modelBuilder.Entity("SafetyAppliaction.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6009),
                            RoleName = "User",
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6009)
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6011),
                            RoleName = "Admin",
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6011)
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6012),
                            RoleName = "Manager",
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6013)
                        },
                        new
                        {
                            RoleId = 4,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6014),
                            RoleName = "Sekretaris",
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6014)
                        },
                        new
                        {
                            RoleId = 5,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6015),
                            RoleName = "DeptHead",
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6015)
                        });
                });

            modelBuilder.Entity("SafetyAppliaction.Models.StatusTransaction", b =>
                {
                    b.Property<int>("StatusTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("StatusTransactionId");

                    b.ToTable("StatusTransactions");

                    b.HasData(
                        new
                        {
                            StatusTransactionId = 1,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6039),
                            StatusName = "Checked",
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6040)
                        },
                        new
                        {
                            StatusTransactionId = 2,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6041),
                            StatusName = "Reviewed",
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6042)
                        },
                        new
                        {
                            StatusTransactionId = 3,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6042),
                            StatusName = "Approved",
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6043)
                        },
                        new
                        {
                            StatusTransactionId = 4,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6044),
                            StatusName = "Rejected",
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6044)
                        });
                });

            modelBuilder.Entity("SafetyAppliaction.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6135),
                            EmployeeId = 1,
                            IsActive = true,
                            PasswordHash = "Password123",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6136),
                            Username = "jdoe"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6138),
                            EmployeeId = 9,
                            IsActive = true,
                            PasswordHash = "Password123",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6139),
                            Username = "dmoore"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6140),
                            EmployeeId = 2,
                            IsActive = true,
                            PasswordHash = "Password123",
                            RoleId = 4,
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6140),
                            Username = "jsmith"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6142),
                            EmployeeId = 8,
                            IsActive = true,
                            PasswordHash = "Password123",
                            RoleId = 4,
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6142),
                            Username = "slee"
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6144),
                            EmployeeId = 7,
                            IsActive = true,
                            PasswordHash = "Password123",
                            RoleId = 5,
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6144),
                            Username = "dwilson"
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6145),
                            EmployeeId = 6,
                            IsActive = true,
                            PasswordHash = "Password123",
                            RoleId = 5,
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6146),
                            Username = "jmiller"
                        },
                        new
                        {
                            UserId = 7,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6148),
                            EmployeeId = 3,
                            IsActive = true,
                            PasswordHash = "Password123",
                            RoleId = 3,
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6148),
                            Username = "rjohnson"
                        },
                        new
                        {
                            UserId = 8,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6150),
                            EmployeeId = 4,
                            IsActive = true,
                            PasswordHash = "Password123",
                            RoleId = 3,
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6150),
                            Username = "edavis"
                        },
                        new
                        {
                            UserId = 9,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6151),
                            EmployeeId = 5,
                            IsActive = true,
                            PasswordHash = "Password123",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6152),
                            Username = "mbrown"
                        },
                        new
                        {
                            UserId = 10,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6153),
                            EmployeeId = 10,
                            IsActive = true,
                            PasswordHash = "Password123",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6154),
                            Username = "staylor"
                        });
                });

            modelBuilder.Entity("SafetyAppliaction.Models.Worklist", b =>
                {
                    b.Property<int>("WorklistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignedEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("WorklistId");

                    b.HasIndex("AssignedEmployeeId");

                    b.HasIndex("RequestId");

                    b.HasIndex("StatusTransactionId");

                    b.ToTable("Worklists");
                });

            modelBuilder.Entity("SafetyApplication.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6094),
                            DepartmentId = 1,
                            EmployeeName = "John Doe",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6095)
                        },
                        new
                        {
                            EmployeeId = 2,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6097),
                            DepartmentId = 1,
                            EmployeeName = "Jane Smith",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6097)
                        },
                        new
                        {
                            EmployeeId = 3,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6099),
                            DepartmentId = 2,
                            EmployeeName = "Robert Johnson",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6099)
                        },
                        new
                        {
                            EmployeeId = 4,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6100),
                            DepartmentId = 2,
                            EmployeeName = "Emily Davis",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6101)
                        },
                        new
                        {
                            EmployeeId = 5,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6102),
                            DepartmentId = 2,
                            EmployeeName = "Michael Brown",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6102)
                        },
                        new
                        {
                            EmployeeId = 6,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6104),
                            DepartmentId = 3,
                            EmployeeName = "Jessica Miller",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6104)
                        },
                        new
                        {
                            EmployeeId = 7,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6105),
                            DepartmentId = 3,
                            EmployeeName = "David Wilson",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6106)
                        },
                        new
                        {
                            EmployeeId = 8,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6107),
                            DepartmentId = 3,
                            EmployeeName = "Sarah Lee",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6107)
                        },
                        new
                        {
                            EmployeeId = 9,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6108),
                            DepartmentId = 1,
                            EmployeeName = "Daniel Moore",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6109)
                        },
                        new
                        {
                            EmployeeId = 10,
                            CreatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6110),
                            DepartmentId = 3,
                            EmployeeName = "Susan Taylor",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 10, 23, 10, 43, 53, 704, DateTimeKind.Local).AddTicks(6111)
                        });
                });

            modelBuilder.Entity("SafetyAppliaction.Models.ApprovalWorkflow", b =>
                {
                    b.HasOne("SafetyAppliaction.Models.StatusTransaction", "ApprovalStatus")
                        .WithMany()
                        .HasForeignKey("ApprovalStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafetyApplication.Models.Employee", "AssignedEmployee")
                        .WithMany("ApprovalWorkflows")
                        .HasForeignKey("AssignedEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafetyAppliaction.Models.RequestTransaction", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovalStatus");

                    b.Navigation("AssignedEmployee");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("SafetyAppliaction.Models.RequestTransaction", b =>
                {
                    b.HasOne("SafetyAppliaction.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafetyApplication.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafetyAppliaction.Models.StatusTransaction", "Status")
                        .WithMany("Requests")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SafetyAppliaction.Models.User", b =>
                {
                    b.HasOne("SafetyApplication.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafetyAppliaction.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SafetyAppliaction.Models.Worklist", b =>
                {
                    b.HasOne("SafetyApplication.Models.Employee", "AssignedEmployee")
                        .WithMany()
                        .HasForeignKey("AssignedEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafetyAppliaction.Models.RequestTransaction", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafetyAppliaction.Models.StatusTransaction", "StatusTransaction")
                        .WithMany()
                        .HasForeignKey("StatusTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedEmployee");

                    b.Navigation("Request");

                    b.Navigation("StatusTransaction");
                });

            modelBuilder.Entity("SafetyApplication.Models.Employee", b =>
                {
                    b.HasOne("SafetyAppliaction.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SafetyAppliaction.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("SafetyAppliaction.Models.StatusTransaction", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("SafetyApplication.Models.Employee", b =>
                {
                    b.Navigation("ApprovalWorkflows");
                });
#pragma warning restore 612, 618
        }
    }
}
